import { Sora } from 'next/font/google'

import Head from 'next/head'

import GlobalStyles from '../assets/styles/global';

const sora = Sora({ subsets: ['latin'] })

export default function App({ Component, pageProps }) {
  return (
    <main className={sora.className}>
      <GlobalStyles />
      <Head>
        <title>My Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </main>
  );

}
